### create user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "jsdfdfdfohn_doe",
  "email": "john154542@example.com",
  "passwordHash": "hhgghashed_password_value",
  "bio": "Hello, I am John.",
  "avatarUrl": "https://example.com/avatar.jpg"
}

### get user by id
GET http://localhost:8080/api/users/1
Accept: application/json

### update user
PUT http://localhost:8080/api/users/1
Content-Type: application/json

{
  "username": "john_doe_updated",
  "email": "john_updated@example.com",
  "passwordHash": "new_hashed_password",
  "bio": "Updated bio for John.",
  "avatarUrl": "https://example.com/new-avatar.jpg"
}

### delete User
DELETE http://localhost:8080/api/users/1

